// <auto-generated />
using System;
using API_Movie_Tunes.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Movie_Tunes.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231007184014_M00")]
    partial class M00
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Movie_Tunes.Models.Filmes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AnoLancamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Classificação")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sinopse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Filmes");
                });

            modelBuilder.Entity("API_Movie_Tunes.Models.TrilhasSonoras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AnoLancamento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FilmesId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrilhaSonorasId")
                        .HasColumnType("int");

                    b.Property<int>("TrilhasSonorasId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FilmesId");

                    b.HasIndex("TrilhaSonorasId");

                    b.ToTable("TrilhasSonoras");
                });

            modelBuilder.Entity("API_Movie_Tunes.Models.TrilhasSonoras", b =>
                {
                    b.HasOne("API_Movie_Tunes.Models.Filmes", null)
                        .WithMany("TrilhaSonoras")
                        .HasForeignKey("FilmesId");

                    b.HasOne("API_Movie_Tunes.Models.TrilhasSonoras", "TrilhaSonoras")
                        .WithMany()
                        .HasForeignKey("TrilhaSonorasId");

                    b.Navigation("TrilhaSonoras");
                });

            modelBuilder.Entity("API_Movie_Tunes.Models.Filmes", b =>
                {
                    b.Navigation("TrilhaSonoras");
                });
#pragma warning restore 612, 618
        }
    }
}
